# Generated by Django 5.1 on 2024-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fixed_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Fixed Income",
            ),
        ),
    ]
