# Generated by Django 5.1 on 2024-08-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fixed_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Fixed Income",
            ),
        ),
    ]
