# Generated by Django 5.1 on 2024-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_fixed_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="default", max_length=50, verbose_name="Avatar"
            ),
        ),
    ]
