# Generated by Django 5.1 on 2024-08-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='defaultAvatar', max_length=50, verbose_name='Avatar'),
        ),
    ]
